Algoritmo "AULA-8-EXERCICIO-2"
// Lógica de Programação
// Professor   : Marcos Monteiro 
// Descrição   : MULTIPLOS DE 2
// Autor(a)    : Everton Oliveira
// Data atual  : 07/11/2022
Var n1 : inteiro;
// Seção de Declarações das variáveis 


Inicio
      escreva ("Os Multiplos de 2 são: ")
      para n1 de 0 ate 100 faca
           se (n1 % 2 = 0) entao
              escreval (n1)
           fimse
      fimpara


Fimalgoritmo