Algoritmo "AULA-8-EXERCICIO-1"
// Lógica de Programação
// Professor   : Marcos Monteiro 
// Descrição   : TABUADA
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/11/2022
Var N, num: inteiro;
// Seção de Declarações das variáveis 


Inicio
      escreva ("Digite um Número de (1 a 10): ")
        leia(num)
          para N de 0 ate 10 faca
            escreval (num," x",N, " =",(N * num))
          fimpara
          escreval ("Resultados do valor digitado.")

Fimalgoritmo