Algoritmo "Exemplo"
// Disciplina   : Lógica de Programação
// Professor   : Marcos Monteiro
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Everton Oliveira
// Data atual  : 01/11/2022
Var endereco: caractere
// Seção de Declarações das variáveis 


Inicio
      escreva ("Digite o Endereço: ")
      leia (endereco)
      escreva ("Endereço: " +endereco)
Fimalgoritmo