Algoritmo "Exercicio-1"

Var nome: CARACTERE;
    peso, altura: REAL;
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Digite o Nome: ")
   leia (nome)

   escreva ("Digite o Peso: ")
   leia (peso)

   escreva ("Digite a Altura: ")
   leia (altura)
   
   escreval ("Nome: ",nome)
   escreval ("Peso: ",peso)
   escreval ("Altura: ",altura)

Fimalgoritmo